flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Ranged-sets-0.3.0
- canteven-http-0.1.1.2
- canteven-log-2.0.0.1
- data-bword-0.1.0.1
- data-dword-0.3.1
- scotty-format-0.1.1.0
- scotty-resource-0.2.0.0
resolver: lts-7.1
